# Generated by Django 4.2.4 on 2023-10-28 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_bookshelf_shoppingcart_shoppingcartitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bookshelfitem',
            name='bookshelf',
        ),
        migrations.RemoveField(
            model_name='shoppingcartitem',
            name='shopping_cart',
        ),
        migrations.AddField(
            model_name='bookshelfitem',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='bookshelf', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppingcartitem',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookshelfitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookshelf', to='shop.shopitem'),
        ),
        migrations.AlterField(
            model_name='shoppingcartitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to='shop.shopitem'),
        ),
        migrations.DeleteModel(
            name='Bookshelf',
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
