# Generated by Django 4.2.4 on 2023-10-22 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='citing_user',
        ),
        migrations.CreateModel(
            name='QuoteCited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cited_at', models.DateTimeField(auto_now_add=True)),
                ('quote_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cited_quote', to='quotes.quote')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cited_quote', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
